name: Ödsmål i bilder
favicon: null
layout_spectrum: 0.27439120784401894
typography_spectrum: 0.9707920523360372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12882182584144175
  lightness: 0.10164769389666617
  saturation: 0.28160200640559196
  rhythmicContrast: 0.7225430856924504
purpose: []
